[package]
name = "cistern_bot"
version = "0.1.0"
authors = ["Izzy <izzy@lskh.io>"]
edition = "2018"

[dependencies]
serenity = "0.5.13"
dotenv = "0.13.0"
structopt = "0.2.15"
lazy_static = "1.3.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
rand = "0.6.5"
regex = "1.1.2"
